### ISSUE TITLE
无法注册RN模块

### ISSUE THREAD

**Issue by Kayshen-X** [react-native-oh-library/react-native-doc-viewer#9]
### 描述 / Description

Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNCDocViewer' could not be found. Verify that a module by this name is registered in the native binary., js engine: hermes 

### 库版本 / Library version

2.7.8-0.0.2

### React Native OpenHarmony version

0.72.32

### 构建类型 / Build type

None

### 设备 / Device

None

### 已悉知 / Acknowledgements

Yes

**Comment by Kayshen-X** [comment]
[https://github.com/react-native-oh-library/react-native-doc-viewer/pulls](url)  已解决

**Comment by yrjwcharm** [comment]
## 可以安装新发布的harmony文档预览库<https://github.com/yrjwcharm/react-native-ohos-docviewer>
